global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Product Order Service
  - job_name: 'product-order-service'
    static_configs:
      - targets: ['product-order-service:8080']
    metrics_path: '/product-order-service/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # MySQL Exporter
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['mysql-exporter:9104']

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Kafka Exporter
  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']

  # JVM Metrics
  - job_name: 'jvm-metrics'
    static_configs:
      - targets: ['product-order-service:8080']
    metrics_path: '/product-order-service/actuator/prometheus'
    params:
      include: ['jvm.*', 'http.*', 'cache.*']
