apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-order-service
  namespace: prod
  labels:
    app: product-order-service
    environment: prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: product-order-service
  template:
    metadata:
      labels:
        app: product-order-service
        environment: prod
    spec:
      containers:
      - name: product-order-service
        image: your-docker-registry.com/product-order-service:latest-prod
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: JVM_OPTS
          value: "-Xmx2g -Xms1g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
        - name: DB_HOST
          value: "prod-mysql-cluster"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "ecommerce_prod"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: product-order-service-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-order-service-secret
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: product-order-service-secret
              key: jwt-secret
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "prod-kafka-cluster:9092"
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: product-order-service-secret
              key: aws-access-key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: product-order-service-secret
              key: aws-secret-key
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: product-order-service-secret
              key: s3-bucket-name
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: product-order-service-secret
              key: cors-allowed-origins
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-order-service-secret
              key: redis-password
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 15
          failureThreshold: 3
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        - name: logs-volume
          mountPath: /app/logs
      volumes:
      - name: config-volume
        configMap:
          name: product-order-service-config
      - name: logs-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: product-order-service
  namespace: prod
  labels:
    app: product-order-service
spec:
  selector:
    app: product-order-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-order-service-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "2000"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - product-order-service.example.com
    secretName: product-order-service-tls
  rules:
  - host: product-order-service.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: product-order-service
            port:
              number: 8080
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: product-order-service-pdb
  namespace: prod
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app: product-order-service
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-order-service-hpa
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-order-service
  minReplicas: 5
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
